name: ml_exciton_model
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python==3.8.20
  - cudatoolkit=12.4
  - pytorch=2.4.1=py3.8_cuda12.4_cudnn9_0
  - tensorboard==2.10.0
  - torchani==2.2
  - pandas==2.0.3
  - mdtraj==1.10.0
  - numba==0.58.1
  - tqdm==4.66.2
  - h5py==3.11.0
  - matplotlib==3.2.2
